INSERT INTO `tag` (`name`) VALUES ("Rock and Roll");
INSERT INTO `tag` (`name`) VALUES ("Hurricanes");
INSERT INTO `tag` (`name`) VALUES ("Architecture");
INSERT INTO `tag` (`name`) VALUES ("Montreal Canadians");
INSERT INTO `tag` (`name`) VALUES ("Game Theory");
INSERT INTO `tag` (`name`) VALUES ("Crystals");
INSERT INTO `tag` (`name`) VALUES ("Aliens");
INSERT INTO `tag` (`name`) VALUES ("Cars");
INSERT INTO `tag` (`name`) VALUES ("Polygons");
INSERT INTO `tag` (`name`) VALUES ("Chocolate");
INSERT INTO `tag` (`name`) VALUES ("Pi");
INSERT INTO `tag` (`name`) VALUES ("Genetics");
INSERT INTO `tag` (`name`) VALUES ("Anthrax");
INSERT INTO `tag` (`name`) VALUES ("Bridges");
INSERT INTO `tag` (`name`) VALUES ("Cars");
INSERT INTO `tag` (`name`) VALUES ("Angles");
INSERT INTO `tag` (`name`) VALUES ("Brain");
INSERT INTO `tag` (`name`) VALUES ("War");
INSERT INTO `tag` (`name`) VALUES ("Nouns");
INSERT INTO `tag` (`name`) VALUES ("Newspaper");
INSERT INTO `tag` (`name`) VALUES ("Earth");
INSERT INTO `tag` (`name`) VALUES ("Pi");
INSERT INTO `tag` (`name`) VALUES ("Computers");
INSERT INTO `tag` (`name`) VALUES ("Binary");
INSERT INTO `tag` (`name`) VALUES ("Eclipse");
INSERT INTO `tag` (`name`) VALUES ("Brain");
INSERT INTO `tag` (`name`) VALUES ("Allergies");
INSERT INTO `tag` (`name`) VALUES ("Basketball");
INSERT INTO `tag` (`name`) VALUES ("Programming");
INSERT INTO `tag` (`name`) VALUES ("Atoms");
INSERT INTO `tag` (`name`) VALUES ("Ants");
INSERT INTO `tag` (`name`) VALUES ("Eclipse");
INSERT INTO `tag` (`name`) VALUES ("Polygons");
INSERT INTO `tag` (`name`) VALUES ("Allergies");
INSERT INTO `tag` (`name`) VALUES ("Allergies");
INSERT INTO `tag` (`name`) VALUES ("Allergies");
INSERT INTO `tag` (`name`) VALUES ("Teeth");
INSERT INTO `tag` (`name`) VALUES ("Ethics");
INSERT INTO `tag` (`name`) VALUES ("Genetics");
INSERT INTO `tag` (`name`) VALUES ("Montreal Canadians");
INSERT INTO `tag` (`name`) VALUES ("Algae");
INSERT INTO `tag` (`name`) VALUES ("Pi");
INSERT INTO `tag` (`name`) VALUES ("Angles");
INSERT INTO `tag` (`name`) VALUES ("Earth");
INSERT INTO `tag` (`name`) VALUES ("Computers");
INSERT INTO `tag` (`name`) VALUES ("Newspaper");
INSERT INTO `tag` (`name`) VALUES ("Pi");
INSERT INTO `tag` (`name`) VALUES ("Angles");
INSERT INTO `tag` (`name`) VALUES ("Soccer");
INSERT INTO `tag` (`name`) VALUES ("Ants");
INSERT INTO `tag` (`name`) VALUES ("Chocolate");
INSERT INTO `tag` (`name`) VALUES ("Montreal Canadians");
INSERT INTO `tag` (`name`) VALUES ("Dogs");
INSERT INTO `tag` (`name`) VALUES ("Bridges");
INSERT INTO `tag` (`name`) VALUES ("Montreal Canadians");
INSERT INTO `tag` (`name`) VALUES ("Aliens");
INSERT INTO `tag` (`name`) VALUES ("Polygons");
INSERT INTO `tag` (`name`) VALUES ("Genetics");
INSERT INTO `tag` (`name`) VALUES ("Research");
INSERT INTO `tag` (`name`) VALUES ("Robots");
INSERT INTO `tag` (`name`) VALUES ("Montreal Canadians");
INSERT INTO `tag` (`name`) VALUES ("Ants");
INSERT INTO `tag` (`name`) VALUES ("Hockey");
INSERT INTO `tag` (`name`) VALUES ("Game Theory");
INSERT INTO `tag` (`name`) VALUES ("Algae");
INSERT INTO `tag` (`name`) VALUES ("Cells");
INSERT INTO `tag` (`name`) VALUES ("Programming");
INSERT INTO `tag` (`name`) VALUES ("Bridges");
INSERT INTO `tag` (`name`) VALUES ("Binary");
INSERT INTO `tag` (`name`) VALUES ("Music");
INSERT INTO `tag` (`name`) VALUES ("Alcohol");
INSERT INTO `tag` (`name`) VALUES ("Basketball");
INSERT INTO `tag` (`name`) VALUES ("Problem Solving");
INSERT INTO `tag` (`name`) VALUES ("Music");
INSERT INTO `tag` (`name`) VALUES ("Newspaper");
INSERT INTO `tag` (`name`) VALUES ("Soccer");
INSERT INTO `tag` (`name`) VALUES ("Anthrax");
INSERT INTO `tag` (`name`) VALUES ("Game Theory");
INSERT INTO `tag` (`name`) VALUES ("Algae");
INSERT INTO `tag` (`name`) VALUES ("Atoms");
INSERT INTO `tag` (`name`) VALUES ("Hurricanes");
INSERT INTO `tag` (`name`) VALUES ("Algae");
INSERT INTO `tag` (`name`) VALUES ("Lasers");
INSERT INTO `tag` (`name`) VALUES ("Polygons");
INSERT INTO `tag` (`name`) VALUES ("Anthrax");
INSERT INTO `tag` (`name`) VALUES ("Atoms");
INSERT INTO `tag` (`name`) VALUES ("Architecture");
INSERT INTO `tag` (`name`) VALUES ("Polygons");
INSERT INTO `tag` (`name`) VALUES ("Programming");
INSERT INTO `tag` (`name`) VALUES ("Graphics");
INSERT INTO `tag` (`name`) VALUES ("Newspaper");
INSERT INTO `tag` (`name`) VALUES ("Earth");
INSERT INTO `tag` (`name`) VALUES ("Architecture");
INSERT INTO `tag` (`name`) VALUES ("Eclipse");
INSERT INTO `tag` (`name`) VALUES ("War");
INSERT INTO `tag` (`name`) VALUES ("Ants");
INSERT INTO `tag` (`name`) VALUES ("Pi");
INSERT INTO `tag` (`name`) VALUES ("Bacteria");
INSERT INTO `tag` (`name`) VALUES ("Ants");
INSERT INTO `tag` (`name`) VALUES ("Baseball");
INSERT INTO `tag` (`name`) VALUES ("Atoms");